version: '3'

services:
  mongo-db:
    image: mongo:3.5
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongoDb:/data/db
    networks:
      - intraHqNetwork

  postgreSql:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgreSql:/var/lib/postgresql/data
    networks:
      - intraHqNetwork

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_ADVERTISED_HOST_NAME=0.0.0.0
      - KAFKA_ADVERTISED_PORT= 9092
    networks:
      - intraHqNetwork
  kafka:
    image: bitnami/kafka:0
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092
#    volumes:
#      - /opt/kafka-persistence:/bitnami
    networks:
      - intraHqNetwork
networks:
  intraHqNetwork:
